name: ishker_24
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+7
# version 7

environment:
  sdk: '>=3.1.0 <4.0.0' 

dependencies:
  flutter:
    sdk: flutter 
  cupertino_icons: ^1.0.2
  mask_text_input_formatter: ^2.4.0
  intl: ^0.18.0
  flutter_svg: ^2.0.7
  flutter_styled_toast: ^2.1.3
  dio: ^5.1.2
  shared_preferences: ^2.1.1
  flutter_bloc: ^8.1.4
  freezed: ^2.3.4
  freezed_annotation: ^2.2.0
  auto_route: ^7.3.2
  easy_localization: ^3.0.2
  get_it: ^7.6.0
  cached_network_image: ^3.2.3
  double_back_to_close_app: ^2.1.0
  pin_code_fields: ^7.3.0
  local_auth: ^2.1.0
  camera: ^0.10.5+8
  permission_handler: ^10.0.0
  google_mlkit_face_detection: ^0.9.0
  url_launcher: ^6.2.3
  path_provider: ^2.0.11
  open_filex: ^4.3.2
  share_plus: ^7.2.1
  device_info_plus: ^9.0.2
  android_id: ^0.3.4
  local_auth_android: ^1.0.36
  local_auth_ios: ^1.1.6
  qr_flutter: ^4.1.0
  lifecycle: ^0.8.0
  pdfx: ^2.6.0
  flutter_cached_pdfview: ^0.4.2
  webview_flutter: ^4.4.2
  syncfusion_flutter_pdfviewer: ^24.2.5
  package_info_plus: ^5.0.1
  flutter_inappwebview: ^6.0.0
  table_calendar: ^3.0.9
  file_picker: ^6.1.1
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter 
  flutter_lints: ^2.0.0
  build_runner: ^2.4.4
  auto_route_generator: ^7.1.1
  
flutter:

  uses-material-design: true
  
  assets:
    - assets/images/
    
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  
